function gen_seq_file(inputDir, outputDir)
%GEN_SEQ_FILE Run all .m files in the demoSeq folder of Pulseq MATLAB toolbox and collect generated .seq files
%
%   This function runs all .m files in the Pulseq demoSeq folder and collects
%   any .seq files generated by these demo scripts. The .seq files are renamed
%   to match their corresponding script names and moved to the output directory.
%
%   gen_seq_file(inputDir, outputDir)
%
%   Inputs:
%   inputDir  - Path to Pulseq demoSeq folder (string)
%   outputDir - Target folder to save all .seq files (string)
%
%   Example:
%   gen_seq_file('C:\pulseq\matlab\demoSeq', 'C:\output')
%   % Runs all demo scripts and moves generated .seq files to output folder
%
%   Notes:
%   - Each demo script runs independently
%   - Generated .seq files are renamed to match script names (e.g., 'epi.m' -> 'epi.seq')
%   - The demoSeq folder is temporarily added to MATLAB path during execution

    if nargin < 2
        error('Need to provide both inputDir and outputDir parameters');
    end

    if ~isfolder(inputDir)
        error('Input directory %s does not exist', inputDir);
    end

    if ~isfolder(outputDir)
        mkdir(outputDir);
    end


    addpath(fileparts(inputDir));
    onCleanup(@() rmpath(fileparts(inputDir)));

    % Find all .m files
    files = dir(fullfile(inputDir, '*.m'));

    for k = 1:numel(files)
        mFilePath = fullfile(files(k).folder, files(k).name);
        fprintf('Running %s ...\n', mFilePath);

        try
            run(mFilePath);
            close all
            
            % Move all newly generated .seq files immediately after running
            seqFiles = dir(fullfile(inputDir, '*.seq'));
            for s = 1:numel(seqFiles)
                src = fullfile(seqFiles(s).folder, seqFiles(s).name);
                
                % Rename .seq file to match script name (remove .m extension)
                [~, scriptName, ~] = fileparts(files(k).name);
                dst = fullfile(outputDir, [scriptName '.seq']);
                
                fprintf('Moving %s -> %s\n', src, dst);
                movefile(src, dst);
            end
            
        catch ME
            warning('Error running %s: %s', files(k).name, ME.message);
        end
    end

    fprintf('All completed.\n');
end
